name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        channel:
          - stable
          - beta
          - nightly
        features:
          - "--features=''"
          - "--all-features"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      run: rustup default ${{ matrix.channel }} && rustup component add clippy && cargo install cargo-llvm-cov
    - name: Build
      run: cargo build --verbose --no-default-features ${{ matrix.features }}
    - name: Run tests
      run: cargo llvm-cov test --text --verbose --no-default-features ${{ matrix.features }}
    - name: Build docs
      run: cargo doc --verbose --no-default-features --no-deps ${{ matrix.features }}
    - name: Run clippy
      run: RUSTFLAGS="-Dwarnings" cargo clippy --verbose --no-default-features ${{ matrix.features }}
      
